"""First-pass macro floorplan of Chameleon on IHP SG13G2.

Places the 27 SRAM macros around a central standard cell region and writes the die area and
the macro instances into ihp_sg13g2/config.yaml (between the "generated by floorplan.py"
markers). Optionally draws the floorplan to scale as SVG.

- Left and right columns: 8 weight macros each, plus the bias macros (4 left, 3 right).
  All in orientation N, with a routing channel in front of their pin edge (the bottom edge,
  where all signal pins are), which opens towards the central region.
- Top of the central region: the activation macros (N, pins facing down into the logic).
- Bottom of the central region: the input macros (FS, pins facing up into the logic).

The channels are sized for the number of wires that leave a macro: 205 signals for a weight
macro, 108 for a bias macro, over the two horizontal routing layers (Metal3, Metal5, 0.42 um
pitch). The gap next to the central region also carries the wires of the bottom bias macros,
which turn north there past the input macros (Metal2, Metal4, 0.48 um pitch).

Usage (from the code directory):
    python ihp_sg13g2/floorplan.py [path/to/chameleon.nl.v] [--svg floorplan.svg]

The macro instance names are read from the synthesized netlist; without an argument, the
netlist of the latest LibreLane run in ihp_sg13g2/runs is used.
"""

import argparse
import os
import re
from pathlib import Path

FLOW_DIR = Path(__file__).resolve().parent
LEF_DIR = Path(os.environ.get("PDK_ROOT", "~/.ciel")).expanduser() / "ihp-sg13g2" / "libs.ref" / "sg13g2_sram" / "lef"
SITE_W, SITE_H = 0.48, 3.78

W_MACRO = "RM_IHPSG13_1P_512x64_c2_bm_bist"   # weights
B_MACRO = "RM_IHPSG13_1P_256x32_c2_bm_bist"   # biases
D_MACRO = "RM_IHPSG13_2P_256x32_c2_bm_bist"   # activations, inputs

# Layout parameters
MARGIN = 50.0        # die edge to macros (core ring, I/O pins)
CHANNEL_W = 70.0     # routing channel in front of the pin edge of each weight macro (205 signals)
CHANNEL_B = 55.0     # same for each bias macro (108 signals)
PAIR_GAP = 10.0      # between two bias macros side by side, and between the two 2P macros
COL_GAP = 100.0      # between a macro column and the central logic region (bias wires turn north here)
CENTER_W = 1440.0    # width of the central region (holds the two 2P macros side by side)


def macro_size(name):
    text = (LEF_DIR / f"{name}.lef").read_text()
    w, h = re.search(r"SIZE\s+([\d.]+)\s+BY\s+([\d.]+)", text).groups()
    return float(w), float(h)


def snap(v, grid):
    return round(round(v / grid) * grid, 3)


def layout():
    ww, wh = macro_size(W_MACRO)
    bw, bh = macro_size(B_MACRO)
    dw, dh = macro_size(D_MACRO)

    col_w = max(ww, 2 * bw + PAIR_GAP)
    col_h = 8 * (wh + CHANNEL_W) + 2 * (bh + CHANNEL_B)
    die_w = 2 * MARGIN + 2 * col_w + 2 * COL_GAP + CENTER_W
    die_h = 2 * MARGIN + col_h

    macros = []  # (kind, label, x, y, w, h, orientation)

    def column(x0, n_bias):
        # Bias rows at the bottom, weights above, each macro with its channel below it
        y = MARGIN
        bias_left = n_bias
        for row in range(2):
            n = min(2, bias_left)
            for i in range(n):
                macros.append(("bias", "B", x0 + i * (bw + PAIR_GAP), y + CHANNEL_B, bw, bh, "N"))
            bias_left -= n
            y += bh + CHANNEL_B
        for i in range(8):
            macros.append(("weight", "W", x0, y + CHANNEL_W, ww, wh, "N"))
            y += wh + CHANNEL_W

    column(MARGIN, 4)
    column(die_w - MARGIN - col_w, 3)

    cx0 = MARGIN + col_w + COL_GAP
    pair_w = 2 * dw + PAIR_GAP
    px0 = cx0 + (CENTER_W - pair_w) / 2
    for i in range(2):
        macros.append(("act", "act", px0 + i * (dw + PAIR_GAP), die_h - MARGIN - dh, dw, dh, "N"))
        macros.append(("in", "in", px0 + i * (dw + PAIR_GAP), MARGIN, dw, dh, "FS"))

    macros = [(k, l, snap(x, SITE_W), snap(y, SITE_H), w, h, o) for k, l, x, y, w, h, o in macros]

    return dict(die_w=snap(die_w, SITE_W), die_h=snap(die_h, SITE_H), col_w=col_w, col_h=col_h,
                ww=ww, wh=wh, bw=bw, bh=bh, dw=dw, dh=dh, cx0=cx0, macros=macros)


COLORS = {"weight": "#4C78A8", "bias": "#F58518", "act": "#54A24B", "in": "#B279A2"}


def svg(fp):
    s = 0.25  # px per um
    pad_l, pad_t, pad_r, pad_b = 130, 115, 330, 95
    W, H = fp["die_w"], fp["die_h"]
    width, height = pad_l + W * s + pad_r, pad_t + H * s + pad_b

    def X(x): return pad_l + x * s
    def Y(y): return pad_t + (H - y) * s  # y up in the layout, down in SVG

    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width:.0f}" height="{height:.0f}" viewBox="0 0 {width:.0f} {height:.0f}" font-family="Helvetica, Arial, sans-serif" font-size="11">',
           '<defs><pattern id="hatch" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">'
           '<line x1="0" y1="0" x2="0" y2="6" stroke="#9aa4ad" stroke-width="1"/></pattern>'
           '<marker id="arr" markerWidth="8" markerHeight="8" refX="4" refY="4" orient="auto-start-reverse">'
           '<path d="M0,0 L8,4 L0,8 z" fill="#333"/></marker></defs>',
           f'<rect width="{width:.0f}" height="{height:.0f}" fill="#ffffff"/>',
           f'<text x="{pad_l}" y="28" font-size="16" font-weight="bold">Chameleon on IHP SG13G2: first-pass macro floorplan</text>',
           f'<text x="{pad_l}" y="48" fill="#555">Die {W:.0f} × {H:.0f} µm = {W * H / 1e6:.2f} mm². Drawn to scale (1 mm = {1000 * s:.0f} px); thick edge = pin edge of each macro.</text>']

    # Die and central logic region
    out.append(f'<rect x="{X(0)}" y="{Y(H)}" width="{W * s}" height="{H * s}" fill="#f7f7f7" stroke="#222" stroke-width="2"/>')
    cx0 = fp["cx0"]
    out.append(f'<rect x="{X(cx0)}" y="{Y(H - 50)}" width="{CENTER_W * s}" height="{(H - 100) * s}" fill="#e8f0e3" stroke="#8aa77a" stroke-dasharray="5,4"/>')
    out.append(f'<text x="{X(cx0 + CENTER_W / 2)}" y="{Y(H / 2) - 8}" text-anchor="middle" font-size="14" fill="#3d5a2e">standard cells</text>')
    out.append(f'<text x="{X(cx0 + CENTER_W / 2)}" y="{Y(H / 2) + 10}" text-anchor="middle" fill="#3d5a2e">PE array, control, SPI, I/O buses</text>')
    out.append(f'<text x="{X(cx0 + CENTER_W / 2)}" y="{Y(H / 2) + 26}" text-anchor="middle" fill="#3d5a2e">(0.70 mm² of cells + hold buffers)</text>')

    for kind, label, x, y, w, h, orient in fp["macros"]:
        # Channel in front of the pin edge (column macros only)
        if kind in ("weight", "bias"):
            ch = CHANNEL_W if kind == "weight" else CHANNEL_B
            out.append(f'<rect x="{X(x)}" y="{Y(y)}" width="{w * s}" height="{ch * s}" fill="url(#hatch)" stroke="none"/>')
        out.append(f'<rect x="{X(x)}" y="{Y(y + h)}" width="{w * s}" height="{h * s}" fill="{COLORS[kind]}" fill-opacity="0.85" stroke="#222" stroke-width="0.8"/>')
        pin_y = y if orient == "N" else y + h
        out.append(f'<line x1="{X(x)}" y1="{Y(pin_y)}" x2="{X(x + w)}" y2="{Y(pin_y)}" stroke="#111" stroke-width="3"/>')
        out.append(f'<text x="{X(x + w / 2)}" y="{Y(y + h / 2) + 4}" text-anchor="middle" fill="#fff" font-weight="bold">{label} ({orient})</text>')

    # Dimension helpers
    def hdim(x1, x2, y, text, above=True):
        yy = Y(y)
        out.append(f'<line x1="{X(x1)}" y1="{yy}" x2="{X(x2)}" y2="{yy}" stroke="#333" marker-start="url(#arr)" marker-end="url(#arr)"/>')
        out.append(f'<text x="{(X(x1) + X(x2)) / 2}" y="{yy - 5 if above else yy + 14}" text-anchor="middle" fill="#333">{text}</text>')

    def vdim(x, y1, y2, text, left=True):
        xx = X(x)
        out.append(f'<line x1="{xx}" y1="{Y(y1)}" x2="{xx}" y2="{Y(y2)}" stroke="#333" marker-start="url(#arr)" marker-end="url(#arr)"/>')
        tx = xx - 6 if left else xx + 6
        out.append(f'<text x="{tx}" y="{(Y(y1) + Y(y2)) / 2}" text-anchor="middle" fill="#333" transform="rotate(-90 {tx} {(Y(y1) + Y(y2)) / 2})">{text}</text>')

    col_w = fp["col_w"]
    hdim(0, W, H + 120, f"die width {W:.1f} µm")
    vdim(-330, 0, H, f"die height {H:.1f} µm")
    hdim(50, 50 + col_w, -90, f"column {col_w:.1f}", above=False)
    hdim(50 + col_w, cx0, -90, f"{COL_GAP:.0f}", above=False)
    hdim(cx0, cx0 + CENTER_W, -90, f"central region {CENTER_W:.1f}", above=False)
    hdim(0, 50, -230, "margin 50", above=False)

    # Macro + channel callout on the top weight of the left column, outside the die
    wm = [m for m in fp["macros"] if m[0] == "weight" and m[2] < W / 2][-1]
    _, _, x, y, w, h, _ = wm
    def tick(yv):
        out.append(f'<line x1="{X(-95)}" y1="{Y(yv)}" x2="{X(-20)}" y2="{Y(yv)}" stroke="#999" stroke-dasharray="2,2"/>')
    for yv in (y + h, y, y - CHANNEL_W):
        tick(yv)
    for y1, y2, t in ((y, y + h, f"W {h:.2f}"), (y - CHANNEL_W, y, f"ch. {CHANNEL_W:.0f}")):
        out.append(f'<line x1="{X(-80)}" y1="{Y(y1)}" x2="{X(-80)}" y2="{Y(y2)}" stroke="#333" marker-start="url(#arr)" marker-end="url(#arr)"/>')
        out.append(f'<text x="{X(-80) - 5}" y="{(Y(y1) + Y(y2)) / 2 + 4}" text-anchor="end" fill="#333" font-size="10">{t}</text>')

    # Legend
    lx, ly = pad_l + W * s + 30, pad_t + 10
    rows = [("weight", f"W: {W_MACRO}", f"{fp['ww']:.2f} × {fp['wh']:.2f} µm, 16×, 205 signal pins"),
            ("bias", f"B: {B_MACRO}", f"{fp['bw']:.2f} × {fp['bh']:.2f} µm, 7×, 108 signal pins"),
            ("act", f"act: {D_MACRO}", f"{fp['dw']:.2f} × {fp['dh']:.2f} µm, 2× (activations), 116 pins"),
            ("in", f"in: {D_MACRO}", f"{fp['dw']:.2f} × {fp['dh']:.2f} µm, 2× (inputs), 116 pins")]
    for i, (k, t1, t2) in enumerate(rows):
        yy = ly + i * 46
        out.append(f'<rect x="{lx}" y="{yy}" width="18" height="18" fill="{COLORS[k]}" stroke="#222"/>')
        out.append(f'<text x="{lx + 26}" y="{yy + 9}" font-size="10.5">{t1}</text>')
        out.append(f'<text x="{lx + 26}" y="{yy + 24}" fill="#555" font-size="10.5">{t2}</text>')
    yy = ly + 4 * 46
    out.append(f'<rect x="{lx}" y="{yy}" width="18" height="18" fill="url(#hatch)" stroke="#9aa4ad"/>')
    out.append(f'<text x="{lx + 26}" y="{yy + 9}" font-size="10.5">pin channel (W {CHANNEL_W:.0f} µm, B {CHANNEL_B:.0f} µm), kept free</text>')
    out.append(f'<text x="{lx + 26}" y="{yy + 24}" font-size="10.5">of standard cells by the macro halo)</text>')
    yy += 46
    out.append(f'<line x1="{lx}" y1="{yy + 9}" x2="{lx + 18}" y2="{yy + 9}" stroke="#111" stroke-width="3"/>')
    out.append(f'<text x="{lx + 26}" y="{yy + 13}" font-size="10.5">pin edge (Metal2 signal pins)</text>')

    macro_area = sum(w * h for *_, w, h, _ in fp["macros"])
    notes = [
        f"Macro area: {macro_area / 1e6:.2f} mm²",
        "Standard cells: 0.70 mm²",
        f"Overall utilization: {(macro_area / 1e6 + 0.70) / (W * H / 1e6) * 100:.0f}%",
        f"Column height: {fp['col_h']:.1f} µm",
        f"  = 8 × (191.34 + {CHANNEL_W:.0f}) + 2 × (118.78 + {CHANNEL_B:.0f})",
        "Orientations: N = pins at bottom,",
        "  FS = flipped, pins at top",
        "Macros block Metal1–Metal4; power grid",
        "  on TopMetal1/2; Metal5 free over macros",
        "Origins snapped to the 0.48 × 3.78 µm site",
        "",
        "Routing estimate (M3+M5 horizontal, 0.42 µm;",
        "  M2+M4 vertical, 0.48 µm):",
        f"  W channel: 205 wires / {2 * CHANNEL_W / 0.42:.0f} tracks = {205 / (2 * CHANNEL_W / 0.42) * 100:.0f}%",
        f"  B channel: 108 wires / {2 * CHANNEL_B / 0.42:.0f} tracks = {108 / (2 * CHANNEL_B / 0.42) * 100:.0f}%",
        f"  gap next to inputs: 216 wires / {2 * COL_GAP / 0.48:.0f} tracks = {216 / (2 * COL_GAP / 0.48) * 100:.0f}%",
    ]
    for i, n in enumerate(notes):
        out.append(f'<text x="{lx}" y="{yy + 50 + i * 16}" font-size="10.5" fill="#333">{n}</text>')

    out.append("</svg>")
    return "\n".join(out)


# Order in which the instances of each memory fill the slots of layout(): the weight macros of
# the 4x4 subsection (genblk1) and the 128-bit pairs (genblk2) stay next to each other
SLOT_ORDER = {
    "weight": [r"genblk1\[0\]", r"genblk1\[1\]"] + [rf"genblk2\[{i}\].*gen_macros\[{j}\]" for i in range(7) for j in range(2)],
    "bias": [rf"bias_memory_inst\.gen_macros\[{i}\]" for i in range(7)],
    "act": [rf"activation_memory_inst\.gen_macros\[{i}\]" for i in range(2)],
    "in": [rf"input_memory\.gen_macros\[{i}\]" for i in range(2)],
}
MACRO_OF_KIND = {"weight": W_MACRO, "bias": B_MACRO, "act": D_MACRO, "in": D_MACRO}
CONFIG_BEGIN = "# BEGIN floorplan (generated by ihp_sg13g2/floorplan.py, do not edit by hand)"
CONFIG_END = "# END floorplan"


def latest_synthesis_netlist() -> Path:
    netlists = sorted((FLOW_DIR / "runs").glob("*/*-yosys-synthesis/chameleon.nl.v"), key=lambda p: p.stat().st_mtime)

    if len(netlists) == 0:
        raise FileNotFoundError("No synthesized netlist found, run LibreLane up to OpenROAD.STAPrePNR first")

    return netlists[-1]


def assign_instances(fp, netlist: Path):
    """Return (macro, instance, x, y, orientation) for every slot of the layout."""
    instances = {}
    for macro, name in re.findall(r"^\s*(RM_IHPSG13_\w+)\s+\\?(\S+)", netlist.read_text(), re.M):
        instances[name] = macro

    placed, used = [], set()
    slots = {kind: [m for m in fp["macros"] if m[0] == kind] for kind in SLOT_ORDER}

    for kind, patterns in SLOT_ORDER.items():
        if len(patterns) != len(slots[kind]):
            raise ValueError(f"{len(patterns)} {kind} instances, but {len(slots[kind])} slots")

        for pattern, (_, _, x, y, _, _, orientation) in zip(patterns, slots[kind]):
            matches = [n for n, m in instances.items() if m == MACRO_OF_KIND[kind] and re.search(pattern, n) and n not in used]

            if len(matches) != 1:
                raise ValueError(f"Pattern {pattern} matches {len(matches)} {MACRO_OF_KIND[kind]} instances: {matches}")

            used.add(matches[0])
            placed.append((MACRO_OF_KIND[kind], matches[0], x, y, orientation))

    if unplaced := set(instances) - used:
        raise ValueError(f"Unplaced macro instances: {sorted(unplaced)}")

    return placed


def config_block(fp, placed) -> str:
    lines = [
        CONFIG_BEGIN,
        "FP_SIZING: absolute",
        f"DIE_AREA: [0, 0, {fp['die_w']}, {fp['die_h']}]",
        "",
        "# The Liberty files of the SRAM macros are patched copies, a temporary workaround for an",
        "# OpenSTA bug (see ihp_sg13g2/patch_sram_lib.py and make ihp_sram_libs)",
        "MACROS:",
    ]
    for macro in (W_MACRO, B_MACRO, D_MACRO):
        lines += [
            f"  {macro}:",
            "    gds:",
            f"      - pdk_dir::libs.ref/sg13g2_sram/gds/{macro}.gds",
            "    lef:",
            f"      - pdk_dir::libs.ref/sg13g2_sram/lef/{macro}.lef",
            "    lib:",
            f'      "*_typ_*": dir::sram_lib/{macro}_typ_1p20V_25C.lib',
            f'      "*_fast_*": dir::sram_lib/{macro}_fast_1p32V_m55C.lib',
            f'      "*_slow_*": dir::sram_lib/{macro}_slow_1p08V_125C.lib',
            "    instances:",
        ]
        for m, name, x, y, orientation in placed:
            if m == macro:
                lines += [f'      "{name}":', f"        location: [{x}, {y}]", f"        orientation: {orientation}"]
    lines.append(CONFIG_END)
    return "\n".join(lines) + "\n"


def write_config(block: str, config: Path):
    text = config.read_text()

    if CONFIG_BEGIN not in text or CONFIG_END not in text:
        raise ValueError(f"Markers not found in {config}")

    start, end = text.index(CONFIG_BEGIN), text.index(CONFIG_END) + len(CONFIG_END) + 1
    config.write_text(text[:start] + block + text[end:])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("netlist", nargs="?", type=Path, default=None)
    parser.add_argument("--config", type=Path, default=FLOW_DIR / "config.yaml")
    parser.add_argument("--svg", type=Path, default=None)
    args = parser.parse_args()

    fp = layout()
    placed = assign_instances(fp, args.netlist or latest_synthesis_netlist())
    write_config(config_block(fp, placed), args.config)
    print(f"Die {fp['die_w']} x {fp['die_h']} um ({fp['die_w'] * fp['die_h'] / 1e6:.2f} mm2), "
          f"{len(placed)} macros written to {args.config}")

    if args.svg:
        args.svg.write_text(svg(fp))
        print(f"Floorplan drawn to {args.svg}")


if __name__ == "__main__":
    main()
